// Mocks generated by Mockito 5.0.14 from annotations
// in rickandmorty/test/features/rickandmorty/domain/usecases/get_char_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rickandmorty/core/error/exception.dart' as _i5;
import 'package:rickandmorty/features/rickandmorty/domain/enitities/person_enitity.dart'
    as _i6;
import 'package:rickandmorty/features/rickandmorty/domain/repository/person_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i3.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PersonEntity>>> getPerson(
          {int? query}) =>
      (super.noSuchMethod(Invocation.method(#getPerson, [], {#query: query}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.PersonEntity>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.PersonEntity>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PersonEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PersonEntity>>> getAllPersons(
          {int? page}) =>
      (super.noSuchMethod(Invocation.method(#getAllPersons, [], {#page: page}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.PersonEntity>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.PersonEntity>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PersonEntity>>>);
  @override
  String toString() => super.toString();
}
